platform :ios, '9.0'

target 'VinIDPayDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VinIDPayDemo
  pod 'VinIDPaySDK', :path => '../'

end
